### ISSUE TITLE
display alternate temperature

### ISSUE THREAD

**Issue by cweinhofer** [balassy/MMM-RemoteTemperature#12]
I recently returned to the US after many years overseas. The US persists with temperature in Fahrenheit and so I have resigned myself to switch my MagicMirror to display that. But I don't want to loose my ability to think in Celsius and would like to see the two temperatures side by side.

Thankfully, your addition of the humidity parameter provided a good base for adding the alternate temperature as another parameter. I believe I was able to do it successfully, despite having almost no experience with JavaScript. I've put in the pull request (  #11 ) so you can look it over and see if everything seems okay.

**Comment by cweinhofer** [comment]
I'm assuming that many people would want to use this with C/ F after the temps.  Adding these in the CSS using 
`.MMM-RemoteTemperature .temp::after {
	content: "C";
}`
seems like a solution that most people could handle without making a lot of extra coding for the module. I'll be happy to update the README if you decide to approve the pull request.

**Comment by cweinhofer** [comment]
Speaking of CSS, the one issue I've been having is that I can't seem to get the module to insert a line break using `.tempalt::after` that way I can with `.temp::after`. Let me know if you have any suggestions.

**Comment by balassy** [comment]
Thank you very much for contributing to this project. 

Honestly I have never thought that there will be a need for another temperature parameter to display mostly because you can always configure your mirror to show multiple instances of this module and configure them differently. I like that your solution is generic, it can be used not only to display Celsius and Fahrenheit values, but to any values, but I _think_ that if the user wants that (s)he would add a module header or a different icon. The MagicMirror has a general configuration setting to choose between Celsius and Fahrenheit values, so I'm not sure that displaying both would fit into the general concepts of the mirror.

Having said that I'm not sure what other users of this module would like to see. So I leave this issue and the PR open, dear visitors, please tell what you think!

Thank you.

**Comment by cweinhofer** [comment]
Thanks for your response. I appreciate your being open to new additions, provided enough people find them useful. For the sake of furthering the discussion, I'll give a few of my thoughts.

I'm guessing you originally created this module to just display the room temperature local to the MM and/or and outside temp. However, in my case, I'm using it to display the readings from a whole series of temperature and humidity sensors all over my house (I currently have 7) -- with the icon indicating the location of the sensor. I tried using multiple instances of the module for alternate values, but found it really difficult to manage. Not only was 14 config entries cumbersome, but I had use a lot of CSS tricks to get all the numbers in nice tight groupings -- and even then it never looked right. But maybe that's just me and most other users are not using this module so extensively.

Having said all that, this discussion made me think that maybe, with a few extra lines of code, this module could be expanded to display a wide set of sensor values. The most obvious scenario for this would be someone who has an Arduino-based (or similar) weather station. In that case, it would be helpful if the module could display temperature, humidity, atmospheric pressure, and wind speed all in one compact set. I will admit my minimal knowledge of code, but I'm wondering if it would be difficult to make it so that it would display a simple temperature "out-of-the-box" (without much complex config), but have lots of other values that the user could "turn on" by adding extra data to the JSON body. The user could then choose what values they wanted to display and add line breaks and or symbols as needed with CSS.

**Comment by cweinhofer** [comment]
Closing this in favor of a possible alternative.
