### ISSUE TITLE
zoom is not universial in CSS, also how to use more than one sensor

### ISSUE THREAD

**Issue by jbat66** [balassy/MMM-RemoteTemperature#32]
Thank you thank you for making this. I have gotten my Yo-Link temp sensors working with your module. This is exactly what I was looking for!!!!!

Some gotcha's I found in setting mine up.

I could not get zoom to work for me, so "zoom: 0.75;" should be replaced with "transform: scale(0.75);" per https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

I would recommend updating your README.md to show how to have more than one sensor in config.js. I thought I could put them all in one 'module' but found I had to have several 'module's of the same name.

So this did not work:
var config = {
  modules: [
    {
      module: 'MMM-RemoteTemperature',
      position: 'top_right',
      config: {
        sensorId: '1',
        icon: 'home', // this should be 'house' as 'home' is not found, but it does get changed to house at fontawesome.
        showMore: true
	sensorId: '2',
        icon: 'tractor',
        showMore: true
      }
    }
  ]
}

I had to do:

  modules: [
    {
      module: 'MMM-RemoteTemperature',
      position: 'top_right',
      config: {
        sensorId: '1',
        icon: 'home', // this should be 'house' as 'home' is not found, but it does get changed to house at fontawesome.
        showMore: true
      }
    },
	{
      module: 'MMM-RemoteTemperature',
      position: 'top_right',
      config: {
        sensorId: '2',
        icon: 'tractor',
        showMore: true
      }
    }
  ]
}

**Comment by jbat66** [comment]
I did note zoom works in Chrome, but not firefox, however using "transform: scale(0.75);" causes the whole module so blow up big and it pushes into the boarders of the screen. So zoom, while not universal, does work for chrome for server only mode, and works for the MM display as it uses chrome.

**Comment by balassy** [comment]
Thank you for your feedback and for reporting this issue.

The README already contains a note about using multiple sensors:

```
This module is capable to display only a single temperature value. If you would like to see the value of more sensors on your mirror, add this module multiple times.
```

Yes, Firefox does not support `zoom`: https://caniuse.com/?search=zoom :( 

Although you can run MagicMirror in any browser it was designed to run in Electron (Chrome), and because the `Customization` section in the README was a community contribution I would not consider this a bug.

If you have a recommended CSS syntax that works cross-browser and does not blow up the module I'm happy to share that in the README, or please submit a pull request.

Thanks for using this module, I hope you like it!
